/* ============================================================
   airbnb-india.com — Site Data (search index)
   Auto-generated by tools/gen-site.js — do not edit by hand.
   ============================================================ */

const DESTINATIONS = [
  {
    "slug": "benaulim",
    "name": "Benaulim",
    "state": "Goa",
    "tagline": "Best airbnb in Benaulim, Goa",
    "img": "https://a0.muscache.com/im/pictures/miso/Hosting-54029360/original/5fe49354-558c-4fa9-9f0b-6ba684ea4bfe.jpeg",
    "url": "destinations/benaulim.html",
    "count": 1,
    "keywords": [
      "best airbnb in benaulim",
      "cheap bnb in benaulim",
      "luxury bnb in benaulim",
      "airbnb benaulim",
      "benaulim goa airbnb",
      "homestays in benaulim"
    ]
  },
  {
    "slug": "goa",
    "name": "Goa",
    "state": "Goa",
    "tagline": "Best airbnb in Goa, Goa",
    "img": "https://a0.muscache.com/im/pictures/6fb02e24-d589-42bd-8b86-41750d91c3d0.jpg",
    "url": "destinations/goa.html",
    "count": 2,
    "keywords": [
      "best airbnb in goa",
      "cheap bnb in goa",
      "luxury bnb in goa",
      "airbnb goa"
    ]
  },
  {
    "slug": "lucknow",
    "name": "Lucknow",
    "state": "Uttar Pradesh",
    "tagline": "Best airbnb in Lucknow, Uttar Pradesh",
    "img": "https://a0.muscache.com/im/pictures/hosting/Hosting-1592729918855637425/original/f9826cd1-b559-468f-bc68-754a745af7a2.jpeg",
    "url": "destinations/lucknow.html",
    "count": 1,
    "keywords": [
      "best airbnb in lucknow",
      "cheap bnb in lucknow",
      "luxury bnb in lucknow",
      "airbnb lucknow",
      "lucknow uttar pradesh airbnb",
      "homestays in lucknow"
    ]
  },
  {
    "slug": "north-goa",
    "name": "North Goa",
    "state": "Goa",
    "tagline": "Best airbnb in North Goa, Goa",
    "img": "https://a0.muscache.com/im/pictures/hosting/Hosting-U3RheVN1cHBseUxpc3Rpbmc6MTU4Mzk0MDg=/original/492dda6c-a57e-416d-8dcd-a7c83db2be0e.jpeg",
    "url": "destinations/north-goa.html",
    "count": 1,
    "keywords": [
      "best airbnb in north goa",
      "cheap bnb in north goa",
      "luxury bnb in north goa",
      "airbnb north goa",
      "north goa airbnb",
      "homestays in north goa"
    ]
  }
];

const LISTINGS = [
  {
    "slug": "benaulim-54029360",
    "name": "Luxury 1 bedroom VILLA with private pool & garden.",
    "city": "Benaulim",
    "state": "Goa",
    "type": "Entire villa",
    "price": null,
    "rating": 4.98,
    "reviews": 117,
    "img": "https://a0.muscache.com/im/pictures/miso/Hosting-54029360/original/5fe49354-558c-4fa9-9f0b-6ba684ea4bfe.jpeg",
    "url": "bnbs/benaulim-54029360.html",
    "blurb": "Villa Gecko Dorado is part of an 18th. C. Heritage Portuguese house. Set in a serene yet vibrant tropical flowering garden, the villa with…",
    "keywords": [
      "best airbnb in benaulim",
      "cheap bnb in benaulim",
      "luxury bnb in benaulim",
      "airbnb benaulim",
      "benaulim goa airbnb",
      "homestays in benaulim"
    ]
  },
  {
    "slug": "goa-38713733",
    "name": "3 Bhk Luxury Beach Villa. HAPPY 2 U Candolim.",
    "city": "Goa",
    "state": "Goa",
    "type": "Entire bungalow",
    "price": null,
    "rating": 4.93,
    "reviews": 308,
    "img": "https://a0.muscache.com/im/pictures/6fb02e24-d589-42bd-8b86-41750d91c3d0.jpg",
    "url": "bnbs/goa-38713733.html",
    "blurb": "U.S.P.  of the villa is  LOCATION, LOCATION, AND LOCATION.   1)  A) Sleeperwood  theme bedroom       B) Bamboo theme                             C)...",
    "keywords": [
      "best airbnb in goa",
      "cheap bnb in goa",
      "luxury bnb in goa",
      "airbnb goa"
    ]
  },
  {
    "slug": "lucknow-1592729918855637425",
    "name": "The Yellow House |Luxury 3bhk Villa in Gomti Nagar",
    "city": "Lucknow",
    "state": "Uttar Pradesh",
    "type": "Entire home",
    "price": null,
    "rating": 4.88,
    "reviews": 42,
    "img": "https://a0.muscache.com/im/pictures/hosting/Hosting-1592729918855637425/original/f9826cd1-b559-468f-bc68-754a745af7a2.jpeg",
    "url": "bnbs/lucknow-1592729918855637425.html",
    "blurb": "Step into The Yellow House, a sunlit and stylish 3-bedroom villa designed for comfort, privacy, and elegance. Nestled in a peaceful neighborhood of...",
    "keywords": [
      "best airbnb in lucknow",
      "cheap bnb in lucknow",
      "luxury bnb in lucknow",
      "airbnb lucknow",
      "lucknow uttar pradesh airbnb",
      "homestays in lucknow"
    ]
  },
  {
    "slug": "goa-45229616",
    "name": "5BHK Villa with Pool and Full Time Chef, Near Baga",
    "city": "Goa",
    "state": "Goa",
    "type": "Entire home",
    "price": null,
    "rating": 4.77,
    "reviews": 103,
    "img": "https://a0.muscache.com/im/pictures/hosting/Hosting-U3RheVN1cHBseUxpc3Rpbmc6NDUyMjk2MTY%3D/original/7bb50571-dcff-45f4-90ae-b0a2c7eabd15.jpeg",
    "url": "bnbs/goa-45229616.html",
    "blurb": "Welcome to The Arowana Palms, a tropical paradise nestled in Arpora. Experience the perfect blend of relaxation and entertainment in our stunning 5...",
    "keywords": [
      "best airbnb in goa",
      "cheap bnb in goa",
      "luxury bnb in goa",
      "airbnb goa"
    ]
  },
  {
    "slug": "north-goa-15839408",
    "name": "Private Pool Villa in Goa",
    "city": "North Goa",
    "state": "Goa",
    "type": "Entire villa",
    "price": null,
    "rating": 4.63,
    "reviews": 68,
    "img": "https://a0.muscache.com/im/pictures/hosting/Hosting-U3RheVN1cHBseUxpc3Rpbmc6MTU4Mzk0MDg=/original/492dda6c-a57e-416d-8dcd-a7c83db2be0e.jpeg",
    "url": "bnbs/north-goa-15839408.html",
    "blurb": "Nestled in the heart of Goa and surrounded by nature, this spacious luxury villa of 2368 sqft comes with its own private pool, modern contemporary ...",
    "keywords": [
      "best airbnb in north goa",
      "cheap bnb in north goa",
      "luxury bnb in north goa",
      "airbnb north goa",
      "north goa airbnb",
      "homestays in north goa"
    ]
  }
];

const POSTS = [
  {
    "slug": "best-airbnb-in-benaulim",
    "title": "Best Airbnb in Benaulim (2026): Top-Rated Stays & Prices",
    "category": "Best",
    "img": "https://a0.muscache.com/im/pictures/miso/Hosting-54029360/original/5fe49354-558c-4fa9-9f0b-6ba684ea4bfe.jpeg",
    "url": "blog/best-airbnb-in-benaulim.html",
    "date": "Aug 14, 2026",
    "excerpt": "The best best Airbnbs in Benaulim, Goa — 1 curated, verified stays with ratings, prices and one-click booking on Airbnb. every budget.",
    "keywords": [
      "best airbnb in benaulim",
      "cheap bnb in benaulim",
      "luxury bnb in benaulim",
      "airbnb benaulim",
      "benaulim goa airbnb",
      "homestays in benaulim"
    ]
  },
  {
    "slug": "cheap-airbnb-in-benaulim",
    "title": "Cheap Airbnbs in Benaulim: 1 Stays Under ₹2,000",
    "category": "Cheap",
    "img": "https://a0.muscache.com/im/pictures/miso/Hosting-54029360/original/5fe49354-558c-4fa9-9f0b-6ba684ea4bfe.jpeg",
    "url": "blog/cheap-airbnb-in-benaulim.html",
    "date": "Aug 14, 2026",
    "excerpt": "The best cheap Airbnbs in Benaulim, Goa — 1 curated, verified stays with ratings, prices and one-click booking on Airbnb. under ₹2,000 per night.",
    "keywords": [
      "best airbnb in benaulim",
      "cheap bnb in benaulim",
      "luxury bnb in benaulim",
      "airbnb benaulim",
      "benaulim goa airbnb",
      "homestays in benaulim"
    ]
  },
  {
    "slug": "luxury-airbnb-in-benaulim",
    "title": "Luxury Airbnbs in Benaulim: Premium Villas & Private Pools",
    "category": "Luxury",
    "img": "https://a0.muscache.com/im/pictures/miso/Hosting-54029360/original/5fe49354-558c-4fa9-9f0b-6ba684ea4bfe.jpeg",
    "url": "blog/luxury-airbnb-in-benaulim.html",
    "date": "Aug 14, 2026",
    "excerpt": "The best luxury Airbnbs in Benaulim, Goa — 1 curated, verified stays with ratings, prices and one-click booking on Airbnb. ₹4,000+ per night.",
    "keywords": [
      "best airbnb in benaulim",
      "cheap bnb in benaulim",
      "luxury bnb in benaulim",
      "airbnb benaulim",
      "benaulim goa airbnb",
      "homestays in benaulim"
    ]
  },
  {
    "slug": "best-airbnb-in-goa",
    "title": "Best Airbnb in Goa (2026): Top-Rated Stays & Prices",
    "category": "Best",
    "img": "https://a0.muscache.com/im/pictures/6fb02e24-d589-42bd-8b86-41750d91c3d0.jpg",
    "url": "blog/best-airbnb-in-goa.html",
    "date": "Aug 14, 2026",
    "excerpt": "The best best Airbnbs in Goa, Goa — 2 curated, verified stays with ratings, prices and one-click booking on Airbnb. every budget.",
    "keywords": [
      "best airbnb in goa",
      "cheap bnb in goa",
      "luxury bnb in goa",
      "airbnb goa"
    ]
  },
  {
    "slug": "cheap-airbnb-in-goa",
    "title": "Cheap Airbnbs in Goa: 2 Stays Under ₹2,000",
    "category": "Cheap",
    "img": "https://a0.muscache.com/im/pictures/6fb02e24-d589-42bd-8b86-41750d91c3d0.jpg",
    "url": "blog/cheap-airbnb-in-goa.html",
    "date": "Aug 14, 2026",
    "excerpt": "The best cheap Airbnbs in Goa, Goa — 2 curated, verified stays with ratings, prices and one-click booking on Airbnb. under ₹2,000 per night.",
    "keywords": [
      "best airbnb in goa",
      "cheap bnb in goa",
      "luxury bnb in goa",
      "airbnb goa"
    ]
  },
  {
    "slug": "luxury-airbnb-in-goa",
    "title": "Luxury Airbnbs in Goa: Premium Villas & Private Pools",
    "category": "Luxury",
    "img": "https://a0.muscache.com/im/pictures/6fb02e24-d589-42bd-8b86-41750d91c3d0.jpg",
    "url": "blog/luxury-airbnb-in-goa.html",
    "date": "Aug 14, 2026",
    "excerpt": "The best luxury Airbnbs in Goa, Goa — 2 curated, verified stays with ratings, prices and one-click booking on Airbnb. ₹4,000+ per night.",
    "keywords": [
      "best airbnb in goa",
      "cheap bnb in goa",
      "luxury bnb in goa",
      "airbnb goa"
    ]
  },
  {
    "slug": "best-airbnb-in-lucknow",
    "title": "Best Airbnb in Lucknow (2026): Top-Rated Stays & Prices",
    "category": "Best",
    "img": "https://a0.muscache.com/im/pictures/hosting/Hosting-1592729918855637425/original/f9826cd1-b559-468f-bc68-754a745af7a2.jpeg",
    "url": "blog/best-airbnb-in-lucknow.html",
    "date": "Aug 14, 2026",
    "excerpt": "The best best Airbnbs in Lucknow, Uttar Pradesh — 1 curated, verified stays with ratings, prices and one-click booking on Airbnb. every budget.",
    "keywords": [
      "best airbnb in lucknow",
      "cheap bnb in lucknow",
      "luxury bnb in lucknow",
      "airbnb lucknow",
      "lucknow uttar pradesh airbnb",
      "homestays in lucknow"
    ]
  },
  {
    "slug": "cheap-airbnb-in-lucknow",
    "title": "Cheap Airbnbs in Lucknow: 1 Stays Under ₹2,000",
    "category": "Cheap",
    "img": "https://a0.muscache.com/im/pictures/hosting/Hosting-1592729918855637425/original/f9826cd1-b559-468f-bc68-754a745af7a2.jpeg",
    "url": "blog/cheap-airbnb-in-lucknow.html",
    "date": "Aug 14, 2026",
    "excerpt": "The best cheap Airbnbs in Lucknow, Uttar Pradesh — 1 curated, verified stays with ratings, prices and one-click booking on Airbnb. under ₹2,000 per night.",
    "keywords": [
      "best airbnb in lucknow",
      "cheap bnb in lucknow",
      "luxury bnb in lucknow",
      "airbnb lucknow",
      "lucknow uttar pradesh airbnb",
      "homestays in lucknow"
    ]
  },
  {
    "slug": "luxury-airbnb-in-lucknow",
    "title": "Luxury Airbnbs in Lucknow: Premium Villas & Private Pools",
    "category": "Luxury",
    "img": "https://a0.muscache.com/im/pictures/hosting/Hosting-1592729918855637425/original/f9826cd1-b559-468f-bc68-754a745af7a2.jpeg",
    "url": "blog/luxury-airbnb-in-lucknow.html",
    "date": "Aug 14, 2026",
    "excerpt": "The best luxury Airbnbs in Lucknow, Uttar Pradesh — 1 curated, verified stays with ratings, prices and one-click booking on Airbnb. ₹4,000+ per night.",
    "keywords": [
      "best airbnb in lucknow",
      "cheap bnb in lucknow",
      "luxury bnb in lucknow",
      "airbnb lucknow",
      "lucknow uttar pradesh airbnb",
      "homestays in lucknow"
    ]
  },
  {
    "slug": "best-airbnb-in-north-goa",
    "title": "Best Airbnb in North Goa (2026): Top-Rated Stays & Prices",
    "category": "Best",
    "img": "https://a0.muscache.com/im/pictures/hosting/Hosting-U3RheVN1cHBseUxpc3Rpbmc6MTU4Mzk0MDg=/original/492dda6c-a57e-416d-8dcd-a7c83db2be0e.jpeg",
    "url": "blog/best-airbnb-in-north-goa.html",
    "date": "Aug 14, 2026",
    "excerpt": "The best best Airbnbs in North Goa, Goa — 1 curated, verified stays with ratings, prices and one-click booking on Airbnb. every budget.",
    "keywords": [
      "best airbnb in north goa",
      "cheap bnb in north goa",
      "luxury bnb in north goa",
      "airbnb north goa",
      "north goa airbnb",
      "homestays in north goa"
    ]
  },
  {
    "slug": "cheap-airbnb-in-north-goa",
    "title": "Cheap Airbnbs in North Goa: 1 Stays Under ₹2,000",
    "category": "Cheap",
    "img": "https://a0.muscache.com/im/pictures/hosting/Hosting-U3RheVN1cHBseUxpc3Rpbmc6MTU4Mzk0MDg=/original/492dda6c-a57e-416d-8dcd-a7c83db2be0e.jpeg",
    "url": "blog/cheap-airbnb-in-north-goa.html",
    "date": "Aug 14, 2026",
    "excerpt": "The best cheap Airbnbs in North Goa, Goa — 1 curated, verified stays with ratings, prices and one-click booking on Airbnb. under ₹2,000 per night.",
    "keywords": [
      "best airbnb in north goa",
      "cheap bnb in north goa",
      "luxury bnb in north goa",
      "airbnb north goa",
      "north goa airbnb",
      "homestays in north goa"
    ]
  },
  {
    "slug": "luxury-airbnb-in-north-goa",
    "title": "Luxury Airbnbs in North Goa: Premium Villas & Private Pools",
    "category": "Luxury",
    "img": "https://a0.muscache.com/im/pictures/hosting/Hosting-U3RheVN1cHBseUxpc3Rpbmc6MTU4Mzk0MDg=/original/492dda6c-a57e-416d-8dcd-a7c83db2be0e.jpeg",
    "url": "blog/luxury-airbnb-in-north-goa.html",
    "date": "Aug 14, 2026",
    "excerpt": "The best luxury Airbnbs in North Goa, Goa — 1 curated, verified stays with ratings, prices and one-click booking on Airbnb. ₹4,000+ per night.",
    "keywords": [
      "best airbnb in north goa",
      "cheap bnb in north goa",
      "luxury bnb in north goa",
      "airbnb north goa",
      "north goa airbnb",
      "homestays in north goa"
    ]
  },
  {
    "slug": "benaulim-54029360",
    "title": "Luxury 1 bedroom VILLA with private pool & garden. — Entire villa in Benaulim, Goa: Details & Price",
    "category": "Listed BNB",
    "img": "https://a0.muscache.com/im/pictures/miso/Hosting-54029360/original/5fe49354-558c-4fa9-9f0b-6ba684ea4bfe.jpeg",
    "url": "blog/benaulim-54029360.html",
    "date": "Aug 14, 2026",
    "excerpt": "Villa Gecko Dorado is part of an 18th. C. Heritage Portuguese house. Set in a serene yet vibrant tropical flowering garden, the villa with…",
    "keywords": [
      "best airbnb in benaulim",
      "cheap bnb in benaulim",
      "luxury bnb in benaulim",
      "airbnb benaulim",
      "benaulim goa airbnb",
      "homestays in benaulim"
    ]
  },
  {
    "slug": "goa-38713733",
    "title": "3 Bhk Luxury Beach Villa. HAPPY 2 U Candolim. — Entire bungalow in Goa, Goa: Details & Price",
    "category": "Listed BNB",
    "img": "https://a0.muscache.com/im/pictures/6fb02e24-d589-42bd-8b86-41750d91c3d0.jpg",
    "url": "blog/goa-38713733.html",
    "date": "Aug 14, 2026",
    "excerpt": "U.S.P.  of the villa is  LOCATION, LOCATION, AND LOCATION.   1)  A) Sleeperwood  theme bedroom       B) Bamboo theme                             C)...",
    "keywords": [
      "best airbnb in goa",
      "cheap bnb in goa",
      "luxury bnb in goa",
      "airbnb goa"
    ]
  },
  {
    "slug": "lucknow-1592729918855637425",
    "title": "The Yellow House |Luxury 3bhk Villa in Gomti Nagar — Entire home in Lucknow, Uttar Pradesh: Details & Price",
    "category": "Listed BNB",
    "img": "https://a0.muscache.com/im/pictures/hosting/Hosting-1592729918855637425/original/f9826cd1-b559-468f-bc68-754a745af7a2.jpeg",
    "url": "blog/lucknow-1592729918855637425.html",
    "date": "Aug 14, 2026",
    "excerpt": "Step into The Yellow House, a sunlit and stylish 3-bedroom villa designed for comfort, privacy, and elegance. Nestled in a peaceful neighborhood of...",
    "keywords": [
      "best airbnb in lucknow",
      "cheap bnb in lucknow",
      "luxury bnb in lucknow",
      "airbnb lucknow",
      "lucknow uttar pradesh airbnb",
      "homestays in lucknow"
    ]
  },
  {
    "slug": "goa-45229616",
    "title": "5BHK Villa with Pool and Full Time Chef, Near Baga — Entire home in Goa, Goa: Details & Price",
    "category": "Listed BNB",
    "img": "https://a0.muscache.com/im/pictures/hosting/Hosting-U3RheVN1cHBseUxpc3Rpbmc6NDUyMjk2MTY%3D/original/7bb50571-dcff-45f4-90ae-b0a2c7eabd15.jpeg",
    "url": "blog/goa-45229616.html",
    "date": "Aug 14, 2026",
    "excerpt": "Welcome to The Arowana Palms, a tropical paradise nestled in Arpora. Experience the perfect blend of relaxation and entertainment in our stunning 5...",
    "keywords": [
      "best airbnb in goa",
      "cheap bnb in goa",
      "luxury bnb in goa",
      "airbnb goa"
    ]
  },
  {
    "slug": "north-goa-15839408",
    "title": "Private Pool Villa in Goa — Entire villa in North Goa, Goa: Details & Price",
    "category": "Listed BNB",
    "img": "https://a0.muscache.com/im/pictures/hosting/Hosting-U3RheVN1cHBseUxpc3Rpbmc6MTU4Mzk0MDg=/original/492dda6c-a57e-416d-8dcd-a7c83db2be0e.jpeg",
    "url": "blog/north-goa-15839408.html",
    "date": "Aug 14, 2026",
    "excerpt": "Nestled in the heart of Goa and surrounded by nature, this spacious luxury villa of 2368 sqft comes with its own private pool, modern contemporary ...",
    "keywords": [
      "best airbnb in north goa",
      "cheap bnb in north goa",
      "luxury bnb in north goa",
      "airbnb north goa",
      "north goa airbnb",
      "homestays in north goa"
    ]
  }
];

const TESTIMONIALS = [
  {
    "id": "tmsrwp87on13",
    "name": "Arjun",
    "text": "Listed my homestay here and got a booking within a week. Free during the launch offer and the page ranks really well.",
    "rating": 5,
    "post": ""
  },
  {
    "id": "tmsrwp87la0s",
    "name": "Rohan & Sneha",
    "text": "Found our perfect Goa honeymoon villa in minutes. Everything was verified and exactly as described — booked straight through Airbnb.",
    "rating": 5,
    "post": "benaulim-54029360"
  },
  {
    "id": "tmsrwottx7ux",
    "name": "Priya Sharma",
    "text": "The villa was stunning, pool was spotless and host super responsive",
    "rating": 5,
    "post": "north-goa-15839408"
  }
];

const NOTIFICATIONS = [];

if (typeof window !== 'undefined') window.AIRBNB_INDIA_DATA = { destinations: DESTINATIONS, listings: LISTINGS, posts: POSTS, testimonials: TESTIMONIALS, notifications: NOTIFICATIONS };
if (typeof module !== 'undefined' && module.exports) module.exports = { DESTINATIONS, LISTINGS, POSTS, TESTIMONIALS, NOTIFICATIONS };
